name: Update Vulnrichment JSON

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone Vulnrichment repository
        run: git clone https://github.com/cisagov/vulnrichment.git

      - name: Combine JSON files
        run: python combine.py
